---
- name: Repo Remi | YUM | Deploy repository
  yum:
    name: "{{ remi_repo_url }}"
    validate_certs: "{{ remi_repo_validate_certs }}"

- name: Repo Remi | Enable/Disable specific remi repository
  block:
    - name: Repo Remi | Make sure yum-utils are present
      yum:
        name: yum-utils

    - name: Repo Remi | Enable remi repository
      command: yum-config-manager --enable {{ item }}
      loop: "{{ remi_repo_enable_list }}"
      when: remi_repo_enable_list is defined

    - name: Repo Remi | Disable remi repository
      command: yum-config-manager --disable {{ item }}
      loop: "{{ remi_repo_disable_list }}"
      when: remi_repo_disable_list is defined

    - name: Repo Remi | Update yum cache
      yum:
        update_cache: yes
  when: remi_repo_enable_list is defined or
        remi_repo_disable_list is defined
